# Generated by Django 2.1.7 on 2019-03-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accept_Reject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField()),
                ('reject', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('docID', models.DateTimeField()),
                ('commentID', models.AutoField(primary_key=True, serialize=False, verbose_name='Comment ID')),
                ('version', models.FloatField()),
                ('comment', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replyID', models.AutoField(primary_key=True, serialize=False, verbose_name='Reply ID')),
                ('reply', models.TextField()),
                ('commentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Comments')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Users')),
            ],
        ),
        migrations.AddField(
            model_name='accept_reject',
            name='commentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Comments'),
        ),
        migrations.AddField(
            model_name='accept_reject',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collab_Docs.Users'),
        ),
    ]
