# Generated by Django 2.1.7 on 2019-03-23 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Docs', '0002_auto_20190323_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 23, 22, 28, 33, 138631)),
        ),
    ]
