# Generated by Django 2.1.7 on 2019-03-26 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Docs', '0003_comments_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 14, 12, 0, 17449)),
        ),
    ]
