# Generated by Django 2.1.7 on 2019-03-26 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Docs', '0005_auto_20190326_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 26, 18, 58, 58, 443980)),
        ),
    ]
